### ISSUE TITLE
Error executing

### ISSUE THREAD

**Issue by digobo** [jjssoftware/asustor-dropbox#3]
Hi, when I run the api I get the error below.

admin@Storage153:/volume0/usr/builtin/etc/crontabs $  python /usr/local/AppCentral/community-dropbox-sync/bin/updown.py -
-token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -y -u / /volume1/Backup_Nube/
Traceback (most recent call last):
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 19, in <module>
    import requests
ImportError: No module named requests

**Comment by bebo-dot-dev** [comment]
The python requests module is not installed by default when python is installed. This script has a dependency on the requests module to enable HTTP requests to be performed; the requests module needs to be installed for this script to work.

**Comment by bebo-dot-dev** [comment]
The requests module can be installed with pip i.e. `pip install requests`
