### ISSUE TITLE
Files in dropbox not downloaded

### ISSUE THREAD

**Issue by 573** [jjssoftware/asustor-dropbox#5]
Hi,
I tried your python script as the original updown.py doesn't seem to download stuff from my dropbox just upload.
Now some files in the dropbox remote do have spaces in their names former which seems to break things:

> Dropbox folder name: /orgzly
Local directory: /home/me/orgzly
file: b'/orgzly/Verschollene Alben.org'
Process terminated early due to exception

**Comment by 573** [comment]
pdb session gives (line numbers slightly off due to inserted `import pdb; pdb.set_trace()` line(s)):

> (Pdb) p ascii_msg
b'Download and save /orgzly/Verschollene Alben.org'
(Pdb) s
TypeError: can't concat str to bytes
> /home/me/.config/nixpkgs/program/python/orgzlysync.py(572)yesno()
-> ascii_msg += '? [Y/n] '

**Comment by 573** [comment]
Workaround: Add
```
.encode('ascii', 'ignore')
```
to the offending line:
```
ascii_msg += '? [Y/n] '
```

**Comment by bebo-dot-dev** [comment]
It sounds like you might have unicode characters in your filename(s) and / or path(s).

Feel free to create a pull request for the required change and I'll take a look. Alternatively live with the workaround. Either way, problem solved ;)

**Comment by 573** [comment]
@jjssoftware lacking the experience to add the req'd changes in a clean and d-r-y manner i would leave it as it is for now. thanks for seeing this through.
